### ISSUE TITLE
Some issues with the getPrices() method

### ISSUE THREAD

**Issue by MachineNeil** [SnaBe/node-bptf-prices#3]
@SnaBe , I would like to sincerely thank you for the resource that you have created and kindly published for the use and learning of Team Fortress 2 players. It is of the highest quality, one of a kind and very educational for beginners in programming, for which I feel indebted to you. 

I have been learning how to use it and I have had a couple of questions that I can't solve, so I am looking for your help.

1. I cannot access all the information on backpack.tf that I can access directly from the site (without being Premium). Here are the shortcomings I have found, although I do not rule out that there may be others:
```
bptf.getPrices({
  raw: 1,
  callback: (err, res) => {
    if (err) {
      console.log(err);
    } else {
      // No Normal quality (0) for some weapons:
      console.log(res.items["Black Rose"].prices);

      // No Unusual quality (5) within the Strange category (11), so prices of Strange Unusuals (and other combinations of qualities, perhaps) are impossible to fetch:
      console.log(res.items["A Hat to Kill For"].prices["11"].Tradable.Craftable); 

      // No prices["15"], which corresponds to Decorated weapons, as per quality schema (https://wiki.teamfortress.com/wiki/WebAPI/GetSchema):
      console.log(res.items["Minigun"].prices); 
      // Decorated weapons are not under the Unique category, either.
      console.log(res.items["Minigun"].prices["6"].Tradable.Craftable); 
      
      // No Circling TF Logo (11) Unusual (5) Birdcage even though they exist (this is just an example, there are a lot more):
      console.log(res.items["Birdcage"].prices["5"].Tradable.Craftable["11"]); 
    }
  },
});
```
I believe part of the issue is due to some prices being severely outdated (>3 years), since items that have recently been priced are not problematic a priori. Also, I cannot find prices for unapplied Unique, Strange or Unusual War Paints (which confers an item the Decorated quality).

2. I cannot seem to find any information regarding the "raw" parameter in your functions. It must be either 1 (for the getPrices method, I believe) or 2 (for getCurrencies), but what is its purpose?

Thank you in advance. Have a nice day!

**Comment by SnaBe** [comment]
Hi @MachineNeil,

First of all, thank you for the kind words, I'm glad you're finding the module useful for more than just learning! 

Issue 1 relates to the [since parameter](https://github.com/SnaBe/node-bptf-prices/wiki#getprices-raw-since-callback-) when calling the method, try it with an older Unix Time like 1325439574 (January 2012). The response only shows items that have been updated since the specified date in Unix Time. 

The default date is December 2020, with not all items having been updated since I initially made the module that year. The reason is not to overload the programmer with data and give them more choices when looking at Backpack.tf prices. 

Here's a simple example that should get you the most item prices for their respective qualities. 

```js
const Prices = require("bptf-prices")

const bptf = new Prices({ apiKey: 'API KEY HERE' })

bptf.getPrices({ raw: 1, since: 1325439574, callback: (err, prices) => {
    if (err) return console.log(err)
    
    console.log(prices.items['Black Rose'].prices['0'])
}})
```
**Editors note**: Remember to set your API key before running the example. 

Regarding issue 2 I'll provide you with [Backpack.tf's official documentation ](https://backpack.tf/api/index.html#/webapi-economy/1f3531f90e005bb62dce8d130ae06de8) for the raw parameter. 

> If set to 1, adds a value_raw to the priceindex objects which represents the value of the item in the lowest currency without rounding. If a high value is set, the raw value will be an average between the low and high value. Setting raw to 2 prevents this behaviour by adding a new field, value_high_raw.

Regarding the War Paints, I'm not entirely sure, they might be too new and therefore have not been updated/added to the API schema. I'll gladly have a look and see if there's anything I can do or perhaps update for it to be possible to find. However, I've just published [bptf-classifieds](https://github.com/SnaBe/node-bptf-classifieds) and you might be able to get an average price by comparing buy and sell prices for certain War Paints.

I hope this helps! If not, you're always welcome to have a look at the [Wiki](https://github.com/SnaBe/node-bptf-prices/wiki#bptf-prices) or post another issue.

And may you have a nice day as well!

Best regards,
SnaBe

**Comment by MachineNeil** [comment]
@SnaBe, thank you kindly for such an insightful answer. I would be delighted if your module could incorporate War Paint data, including their variations and qualities. If implementing this update were not technically feasible, know that the developers over at backpack.tf really do take the opinions of developers and API users into consideration from what I know and have seen in forums.backpack.tf - they would surely find your take on their v4 valuable to improve their API.

Lastly, I have one more question: how can I search for items that possess multiple qualities, such as Strange Unusual/Unique/Normal/Vintage/Haunted/Genuine and possibly others? 

Thank you once again, and take care.
Neil.

**Comment by SnaBe** [comment]
To my knowledge items with multiple (or elevated) qualities are not supported by the current API schema. I would suggest you use the Classified listings as a reference for pricing them or use the API price as a base and manually add a percentage increase for strange items. 

Here's an example with [bptf-classifieds](https://github.com/SnaBe/node-bptf-classifieds).

```js
const { Classifieds } = require("bptf-classifieds")

const classifieds = new Classifieds({
    token: '56c21c9edea9e9477c1222f2'
})

classifieds.getListings({ sku: 'Strange Scorching Flames Private Eye', callback: (error, response) => {
    if (error) return

    console.log(response.listings)
}})
```

I'll investigate the War Paint situation and see if there's anything I can do for a future release.

Best regards,
SnaBe

**Comment by MachineNeil** [comment]
Interesting, thank you @SnaBe. As I understand it, items with elevated qualities might only logged onto [next.backpack.tf](https://next.backpack.tf/), as you can see:

![next](https://github.com/SnaBe/node-bptf-prices/assets/112895385/426ddee9-d98b-4bf8-9d12-1023e199a80b)
![old](https://github.com/SnaBe/node-bptf-prices/assets/112895385/0de2ce4c-73e6-48b5-b98b-39f5d7301222)

The same happens with [War Paints](https://next.backpack.tf/war-paints) and possibly spells, although I could be mistaken. Nonetheless, I am unsure whether their [API](https://next.backpack.tf/developer) is any different from their V4.

Thank you once again for the tools you share, they are incredibly helpful. I am looking forward to new projects and updates from you!

Cheers,
Neil

**Comment by SnaBe** [comment]
Interesting, I did not know Backpack.tf was working on a new interface. Once the migration from old to new has been completed, they might migrate the internal API changes to the public one we use. 

I'll reopen this issue in case there's a development in the War Paint case or changes to the API schema.

Best regards,
SnaBe
